### Site Settings ###
title               : Camila Oliveira
description         : >-
                      Physical engineer by education, data engineer by profession. 
                      Always learning, searching and improving. 
                      Based in Barcelona, Spain
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : cammiilla/cammiilla.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
open_new_tab        : false                             # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : Camila Oliveira
  image             : https://lh3.googleusercontent.com/drive-viewer/AFGJ81rXyjxr7GNFcexVw34_RA-T6LqDq1KN13LTlDgKUP9HF4vXnj3LgxTzJ02UhxliWTLk-0SO48-zUNDZ18cq-hRGrUSZ=s1600
  email             : cammiillac@gmail.com
  github            : cammiilla
  instagram         : @cammiillac
  linkedin          : camila-oliveira-cardoso


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: true                                        # Set true to enable analytics
  google:
    tracking_id: G-7GX6JHWKPD


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
